---
title: "Boxplot"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Libraries

Download necessary libraries

```{r}
library(tidyverse)
library(googlesheets4)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)
```

## Download data

Get data from Google sheets

```{r}
ss <- "https://docs.google.com/spreadsheets/d/1RefL2DMmCoOjCcIiaYgSnuDF34ORQFAZKu3nkaoS6o8/edit?gid=1138676736#gid=1138676736"
df_raw <- read_sheet(ss, sheet = "Projects_2")
df <- df_raw %>% janitor::clean_names()
```

## Filter and plot

Filter out countries and MW from data set, remove extreme outliers and plot a boxplot

```{r}
sel<- df %>% 
  filter(
    electrolyser_consumption_mw !="N/A") %>% # Ta bort värden > 1000 
  select(country, project_name, status, electrolyser_consumption_mw)%>%
  mutate(electrolyser_consumption_mw = as.numeric(electrolyser_consumption_mw))
 
box<- sel %>% 
  ggplot(aes(x = country, y = electrolyser_consumption_mw,
             label = project_name,
             fill = country)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.7) +
  scale_y_log10()+
  facet_wrap(~status)+
  labs(x = "Country", y = "MW", title = "Electrolyser Consumption by Country") +
  theme_minimal() +
  theme(legend.position = "none")  # Valfritt, om du vill dölja legenden

box
ggplotly(box)


```


# status
```{r}

status <- sel %>% 
  group_by(status, country) %>% 
  summarise(mw = sum(electrolyser_consumption_mw), n = n())

st_plot <- status %>% 
  ggplot(aes(mw, status, 
             label = n,
             fill = country)) + 
  geom_col() +
  theme_minimal() +
  labs(y = "")
  
st_plot
ggplotly(st_plot)

```


Såhär ser den ut med outlyers

```{r}
sel<- df %>% filter(electrolyser_consumption_mw !="N/A")%>% # Ta bort värden > 1000 
  select(country,electrolyser_consumption_mw)%>%
  mutate(electrolyser_consumption_mw = as.numeric(electrolyser_consumption_mw))
 
sel %>% ggplot(aes(x = country, y = electrolyser_consumption_mw, fill = country)) +
  geom_boxplot() +
  labs(x = "Country", y = "MW", title = "Electrolyser Consumption by Country") +
  theme_minimal() +
  theme(legend.position = "none")  # Valfritt, om du vill dölja legenden
```

```{r}
# Filtrera, välj och förbered data
sel <- df %>% 
  filter(electrolyser_consumption_mw != "N/A") %>%  # Ta bort värden > 2000 
  select(country, electrolyser_consumption_mw) %>%
  mutate(electrolyser_consumption_mw = as.numeric(electrolyser_consumption_mw))

# Skapa boxplot med unika färger för varje land
sel %>% ggplot(aes(x = country, y = electrolyser_consumption_mw, fill = country)) +
  geom_boxplot(outlier.shape = NA) +
  labs(x = "Country", y = "MW", title = "Electrolyser Consumption by Country") +
  scale_y_continuous(limits = c(-5, 800)) + 
  theme_minimal() +
  theme(legend.position = "none")  # Valfritt, om du vill dölja legenden hallo
```
