---
title: "MW per year"
format: html
editor: visual
---

## Libraries

```{r}
library(tidyverse)
library(googlesheets4)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)
```

## Organizing data

```{r}
ss <- "https://docs.google.com/spreadsheets/d/1RefL2DMmCoOjCcIiaYgSnuDF34ORQFAZKu3nkaoS6o8/edit?gid=1138676736#gid=1138676736" 

# Read project sheet and clean 
df_raw <- read_sheet(ss, sheet = "main_projects") 
df <- df_raw %>% 
  janitor::clean_names() 

mw_year <- df%>%
  select(date_online,electrolyser_mw)%>%  
  filter(electrolyser_mw != "N/A", date_online != "N/A")%>%
  mutate(date_online=as.numeric(date_online),electrolyser_mw=as.numeric(electrolyser_mw) )

summarized_data <- mw_year %>%
  filter(date_online>2021)%>%
  group_by(date_online) %>%
  summarize(total_mw = sum(electrolyser_mw))

```

## Plot bars

```{r}
ggplot(summarized_data, aes(x = factor(date_online), y = total_mw)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(
    title = "Total buildout MW per Year",
    x = "Year",
    y = "Total MW"
  ) +
  theme_minimal()
```
