---
title: "Nordic Hydrogen Valleys"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: flatly
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(googlesheets4)
library(shiny)
library(shinyWidgets)
library(tidyverse)
library(stringr)
library(lubridate)
library(plotly)
library(ggthemes)
library(leaflet)
library(visNetwork)

```


```{r}
# read data
googlesheets4::gs4_auth()

ss <- "https://docs.google.com/spreadsheets/d/1xzpre5Ej_7OEGRU4EA7KZuMQnSz5YCyTx5Sdbml6bQE/edit#gid=0"
df_main_raw <- read_sheet(ss, sheet = "Main")
geo_locations_raw <- read_sheet(ss, sheet = "locations_coord", range = "B:E")

geo <- geo_locations_raw %>% select(-Comment) %>% rename(Location = Name2) %>% unique()

jobs <- df_main_raw %>% 
  left_join(geo, by = "Location") %>%
  mutate(Country = case_when(
    str_detect(ID, pattern ="^1") ~ "SE", 
    str_detect(ID, pattern ="^2") ~ "NO",
    str_detect(ID, pattern ="^3") ~ "DK"
  )) %>%
  filter(!is.na(Longitude)|!is.na(Latitude)) %>%
  filter(Scrape_date >= "2023-08-20")


tot_jobs <- jobs %>% 
  filter(Company != "!!!NEW_COMPANY!!!") %>%
  count(Company, name = "total") %>%
  arrange(desc(total))
  
companies <- jobs %>% 
  group_by(Company, Country) %>% 
  summarise(n = n()) %>%
  arrange(desc(n)) %>% 
  left_join(tot_jobs) %>%
  ungroup()
  

countries <- jobs %>% 
  select(Company, Location, Country) %>%
  pivot_longer(Company:Location, names_to = "type", values_to = "id") %>%
  select(-type) %>%
  unique() %>%
  group_by(id) %>%
  summarise(group = paste(unique(Country), collapse = ", "))

country_combinations <- countries %>% pull(group) %>% unique()


#centrera kartan
lon_med <- (max(geo$Longitude)-min(geo$Longitude))/2 +min(geo$Longitude)
lat_med <- (max(geo$Latitude)-min(geo$Latitude))/2 +min(geo$Latitude)



```


```{r}

#create custom pallet 
#industry_colors <- c(
#  "Iron and steel" = "#7D7D7D",
#  "Pulp and paper" = "#33A02C",
#  "Food" = "#B2DF8A",
#  "Heat and power" = "#FF7F00",
#  "Chemicals" = "#CAB2D6",
#  "Cement and minerals" = "#FB9A99",
#  "Other" = "#A6CEE3",
#  "Metals" = "#FDBF6F",
#  "Refinery" = "#7570B3"
#)

country_p <- viridis::plasma(length(country_combinations))
network_colors <- tibble(combinations = country_combinations, colors = country_p)
names(country_p) <- country_combinations




# custom theme
cust_theme <- theme_fivethirtyeight()+
  theme(legend.position = "none",
        axis.title.x=element_text(face="bold", colour="#666666"),
        axis.title.y=element_text(face="bold", colour="#666666")
        )

```



Organisations
======================================

Sidebar {.sidebar}
-------------------------------------

```{r}
hr()

numericInput("max_org_loc", "Top Organisations/Locations", value = 20, min = 0, max = nrow(companies), step = 1)

hr()

react_companies <- reactive({
  tot_jobs %>% 
    slice_head(n = input$max_org_loc)
})


```



Column { .tabset}
-----------------------------------------------------------------------

### Main Recruiters
```{r}

renderPlotly({
  comp <- react_companies()

  top_comp <- comp %>% pull(Company)
  
  p_Org <- companies %>%
    filter(Company %in% top_comp) %>%
  ggplot(aes(x= n, 
             y = reorder(Company, total), 
             fill = Country, 
             text = paste(Country, ":", n))) + 
  geom_col(alpha = 0.65) +
  scale_fill_manual(values =country_p)+
  cust_theme+
  labs(x= "Nr of new jobs", y = " ")

ggplotly(p_Org, tooltip = "text")
  
}
)

```
> Main recruiters based on on total number of job adds in all countries.

### Main locations
```{r}
renderPlotly({

p_loc <- jobs %>% 
  group_by(Location, Country) %>% 
  summarise(n = n()) %>% 
  ungroup() %>%
  arrange(desc(n)) %>%
  slice_max(n = input$max_org_loc, order_by = n) %>% 
  ggplot(aes(x= n, 
             y = reorder(Location,n), 
             fill = Country, 
             text = paste(Country, ":", n))) +
  geom_col(alpha = 0.65) +
  scale_fill_manual(values =country_p)+
  cust_theme+
  labs(x= "Nr of new jobs", y = " ")

ggplotly(p_loc, tooltip = "text")
})


```


### Data Table
```{r}
DT::renderDataTable({
  h2_org <- req(react_companies())
  DT::datatable(h2_org, extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('csv'))
    ) 
  })
```



Network (2-mode)
=============================================

```{r}

numericInput("nr_jobs", "Min. recruitments per organisation", value = 5, min = 0, max = max(companies$n), step = 1)


renderVisNetwork({

n1 <- jobs %>% count(Company) %>% 
  mutate(type = "Org") %>% 
  rename(id = Company)

n2 <- jobs %>% count(Location) %>% 
  mutate(type = "Locations") %>% 
  rename(id = Location)


nodes <- bind_rows(n1, n2) %>%
  mutate(size = round(scales::rescale(n, to = c(1, 10)))) %>%
  mutate(size = round(sqrt(n) +10)) %>%
  mutate(title = paste0(id, "<br> Jobs: ", n),
         shape = ifelse(type == "Org", "dot", "square"),
         opacity = 1) %>%
  filter(n >= input$nr_jobs) %>%
  left_join(geo, by =c("id" = "Location")) %>%
  left_join(countries)
  
count(nodes, id) %>% filter(n>1)


edges <- jobs %>% 
  count(Company, Location) %>% 
  rename(from = Company, to = Location) %>%
  mutate(width = round(log(n)+1)) %>%
  mutate(title = paste("Jobs:", n))

network_plot <- visNetwork(nodes, edges)

for(i in 1:length(network_colors$combinations)) {
  network_plot <- network_plot %>% 
    visGroups(groupname = network_colors$combinations[i], 
              color = list(background = network_colors$colors[i], border = network_colors$colors[i]))
}

network_plot %>%
  visOptions(
    highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE), 
    selectedBy = "group")

})


```
>Mode 2 network, connecting recruiters to places. Please wait for the network to load. It takes looong..

H2 Map
=====================================================
```{r}

renderLeaflet(
  {

df <- jobs %>% 
  select(Company, Location, Title, Longitude, Latitude)

leaflet(df) %>% 
  addTiles() %>% 
  #setView(lng = lon_med, lat = lat_med, zoom = 4.5) %>% # center the map and decide on zoom-level
  addMarkers(lng = ~Longitude, lat = ~Latitude, 
             clusterOptions = markerClusterOptions(),
             popup = ~paste0(Company, "<br>", Location, "<br>", Title)
               )

  }
)


```



Time Series
=====================================================

```{r}

# Define the starting month
start_month <- as.Date("2023-01-01") 

ads <- df_main_raw %>% 
  mutate(Country = case_when(
    str_detect(ID, pattern ="^1") ~ "SE", 
    str_detect(ID, pattern ="^2") ~ "NO",
    str_detect(ID, pattern ="^3") ~ "DK"),
    Scrape_date = as.Date(Scrape_date, format = "%Y-%m-%d"), 
    Month = floor_date(Scrape_date, "month")) %>% 
  filter(Month >= start_month) %>% 
  group_by(Month, Country) %>% 
  summarise(n = n()) %>%
  select(Country, Month, n)

p_Ads <- ads %>%
  ggplot(aes(x = Month, y = n, color = Country)) +
  geom_line() +
  labs(x = "Month", y = "Nr of new jobs") +
  theme_minimal()

ggplotly(p_Ads, tooltip = "text")

```

Om
==============================

```{r}
hr()

```

Syftet med den här sidan är att ..

```{r}
hr()
```